safe:      true
permalink: pretty
exclude:   [ Gemfile, Gruntfile.js, node_modules, package.json, README.md ]

meta:
    title:  Eric GELOEN
    author: Eric GELOEN
    email:  geloen.eric@gmail.com
    url:    http://egeloen.github.io
